version: '3.8'

services:
  ghg-monitor-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - JWT_SECRET=development-secret-key
      - DATA_PATH=/app/data
      - LOG_LEVEL=debug
    volumes:
      - ./data:/app/data
      - ./backend/src:/app/src
    restart: unless-stopped
    
  ghg-monitor-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3001
      - VITE_APP_NAME=GHG Monitor
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - ghg-monitor-backend
    restart: unless-stopped